version: "3.8"

services:
    app:
    build: .
    container_name: react_app
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    volumes:
      - .:/app
      - /app/node_modules
    restart: always