version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/frontend # Маппинг в WORKDIR контейнера
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Для hot-reload
    command: npm start
