name: deploy_prod

on:
  workflow_dispatch

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t ed25519 81.19.136.114 >> ~/.ssh/known_hosts
      - name: Deploy via SSH
        run: |
          ssh elmir@81.19.136.114 << EOF
            cd photopamyannik-front
            git pull origin main 
            docker compose up --build
          EOF

#            cd /path/to/your/project
#            git pull
#            docker compose -f docker-compose.prod.yml pull
#            docker compose -f docker-compose.prod.yml up -d --build